### ISSUE TITLE
Проблемы с незакрытыми транзакциями

### ISSUE THREAD

**Issue by avbelyaev** [YetAnotherTimeTracker/yatt#32]
из диалога:

Anthony Belyaev, [30.11.17 08:35]
Good morning

Asuna Yuuki, [30.11.17 08:35]
Sorry, there were an error: (psycopg2.ProgrammingError) can't adapt type 'Task' [SQL: 'UPDATE projects SET next_task_id=%(next_task_id)s WHERE projects.id = %(projects_id)s'] [parameters: {'next_task_id': <models.task.Task object at 0x7f11500f8940>, 'projects_id': 1}]

Anthony Belyaev, [30.11.17 08:35]
/hi

Asuna Yuuki, [30.11.17 08:35]
Sorry, there were an error: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.ProgrammingError) can't adapt type 'Task' [SQL: 'UPDATE projects SET next_task_id=%(next_task_id)s WHERE projects.id = %(projects_id)s'] [parameters: {'next_task_id': <models.task.Task object at 0x7f11500f8940>, 'projects_id': 1}]

проблема с незавршенными транзакциями. psycopg2 открывает их даже на `SELECT ...`

гугл говорит о том, что это частая проблема а в FAQ psycopg2 есть, кажется, и решение - автокоммиты транзакций. либо пройтись по всем имеющимся сервисам `/services` и просмотреть на наличие незакрытых

**Comment by avbelyaev** [comment]
```
2017-11-30 12:41:28,045 - handlers.interaction_handler - INFO - Incoming message from anthonybelyaev (316956601)): still running?
2017-11-30 12:41:28,048 - handlers.interaction_handler - INFO - curr_state: State.ALL_TASKS, curr_command: CommandType.ECHO
2017-11-30 12:41:28,055 - handlers.interaction_handler - INFO - rendering state: new_task_state
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'Task'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/handlers/interaction_handler.py", line 51, in handle
    handler(bot, update, curr_context)
  File "/app/services/state_service.py", line 53, in new_task_state
    new_task = task_service.create_task(update)
  File "/app/services/task_service.py", line 67, in create_task
    project_service.update_nearest_task_for_project(project.get_id())
  File "/app/services/project_service.py", line 50, in update_nearest_task_for_project
    saved_proj = save(project)
  File "/app/utils/service_utils.py", line 35, in save
    db_session.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2177, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2297, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2261, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 737, in _emit_update_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'Task' [SQL: 'UPDATE projects SET next_task_id=%(next_task_id)s WHERE projects.id = %(projects_id)s'] [parameters: {'next_task_id': <models.task.Task object at 0x7f52881629e8>, 'projects_id': 1}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/updater.py", line 149, in _thread_wrapper
    target(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 219, in start
    self.process_update(update)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 270, in process_update
    handler.handle_update(update, self)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/messagehandler.py", line 169, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/app/handlers/interaction_handler.py", line 64, in handle
    log.error('Error has been caught in handler: ', e)
Message: 'Error has been caught in handler: '
Arguments: (ProgrammingError("(psycopg2.ProgrammingError) can't adapt type 'Task'",),)
```

**Comment by avbelyaev** [comment]
```
Sorry, there were an error: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) duplicate key value violates unique constraint "users_pkey"
DETAIL:  Key (id)=(316956601) already exists.
 [SQL: 'INSERT INTO users (id, username, first_name, is_active) VALUES (%(id)s, %(username)s, %(first_name)s, %(is_active)s)'] [parameters: {'id': 316956601, 'username': 'anthonybelyaev', 'first_name': 'Anthony', 'is_active': True}]
```
возникла такая проблема после 14 часов работы бота. на /hi. 

после этого создал таск и вызвал заново и все норм. вероятно, надо отключить автокоммиты
